server:
  port: 8080

spring:
  application:
    name: university_simple_project

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true

promql.host: ${PROMETHEUS_HOST}